import {
  SummaryData,
  ReportsResponse,
  CatalogStepItem,
  UsageData,
  LeadsResponse,
  AnalyticsData,
  BlogData,
  InventoryData,
} from './types';

export const MOCK_SUMMARY: SummaryData = {
  build: 'ec0382ed',
  leads: { value: 1420, new: 184 },
  reports_total: 4892,
  reports_period: { value: 618 },
  cost: { value: 84.62, prev: 71.30 },
  calls: { value: 1840, prev: 1520 },
  views: { value: 24890, prev: 19400 },
  comments: { value: 312, prev: 245 },
  events: { value: 9240, prev: 7890 },
};

export const MOCK_REPORTS: ReportsResponse = {
  total: 618,
  usd_rate: 96.40,
  rows: [
    {
      id: 'rep-9481',
      created: Math.floor(Date.now() / 1000) - 1800,
      kind: 'Экспресс-аудит сайта',
      who: 'Михаил Соколов',
      username: 'm_sokolov_pro',
      url: 'https://alfa-logistics.ru',
      score: 84,
      cost_rub: 14.85,
      link: 'https://uspeshnyy.ru/r/9481',
      spend: {
        models: [{ provider: 'OpenRouter', model: 'anthropic/claude-3.5-sonnet' }],
        tin: 6420,
        tout: 1890,
        cost: 0.154,
      },
      summary: 'Аудит конверсии посадочной страницы. Выявлены критические ошибки в мобильной шапке и форме заявки.',
      status: 'completed',
    },
    {
      id: 'rep-9480',
      created: Math.floor(Date.now() / 1000) - 7200,
      kind: 'SEO-разбор семантики',
      who: 'Елена Васильева',
      username: 'elena_ecom',
      url: 'https://nordic-wool.store',
      score: 71,
      cost_rub: 9.42,
      link: 'https://uspeshnyy.ru/r/9480',
      spend: {
        models: [{ provider: 'Google', model: 'gemini-3.6-flash' }],
        tin: 12400,
        tout: 2410,
        cost: 0.098,
      },
      summary: 'Кластеризация запросов и поиск упущенной семантики в категории зимнего трикотажа.',
      status: 'completed',
    },
    {
      id: 'rep-9479',
      created: Math.floor(Date.now() / 1000) - 14400,
      kind: 'Анализ оффера и УТП',
      who: 'Даниил Краснов',
      username: 'krasnov_saas',
      url: 'https://quicklead.io',
      score: 92,
      cost_rub: 18.20,
      link: 'https://uspeshnyy.ru/r/9479',
      spend: {
        models: [{ provider: 'Anthropic', model: 'claude-3-7-sonnet' }],
        tin: 8900,
        tout: 2100,
        cost: 0.189,
      },
      summary: 'Глубокий разбор ценностного предложения B2B SaaS. Сформированы 3 альтернативных позиционирования.',
      status: 'completed',
    },
    {
      id: 'rep-9478',
      created: Math.floor(Date.now() / 1000) - 28800,
      kind: 'Технический чек-лист',
      who: 'Артём Гусев',
      username: 'gusev_dev',
      url: 'https://proremont-spb.ru',
      score: 63,
      cost_rub: 6.15,
      link: 'https://uspeshnyy.ru/r/9478',
      spend: {
        models: [{ provider: 'DeepSeek', model: 'deepseek-chat-v3' }],
        tin: 9400,
        tout: 1540,
        cost: 0.064,
      },
      summary: 'Проверка TTFB, LCP, метатегов и дублей страниц. Зафиксирована медленная загрузка изображений.',
      status: 'completed',
    },
    {
      id: 'rep-9477',
      created: Math.floor(Date.now() / 1000) - 43200,
      kind: 'Экспресс-аудит сайта',
      who: 'Ольга Николаева',
      username: 'olga_nik',
      url: 'https://dental-comfort.ru',
      score: 88,
      cost_rub: 14.10,
      link: 'https://uspeshnyy.ru/r/9477',
      spend: {
        models: [{ provider: 'OpenRouter', model: 'anthropic/claude-3.5-sonnet' }],
        tin: 5980,
        tout: 1720,
        cost: 0.146,
      },
      summary: 'Аудит стоматологической клиники. Рекомендовано добавить калькулятор лечения и отзывы врачей.',
      status: 'completed',
    },
    {
      id: 'rep-9476',
      created: Math.floor(Date.now() / 1000) - 72000,
      kind: 'Аудит конверсии воронки',
      who: 'Игорь Мельников',
      username: 'melnikov_biz',
      url: 'https://crm-consulting.agency',
      score: 79,
      cost_rub: 15.60,
      link: 'https://uspeshnyy.ru/r/9476',
      spend: {
        models: [{ provider: 'OpenRouter', model: 'anthropic/claude-3.5-sonnet' }],
        tin: 7100,
        tout: 1950,
        cost: 0.162,
      },
      summary: 'Анализ пути лида от первого клика до квалифицированной заявки.',
      status: 'completed',
    },
    {
      id: 'rep-9475',
      created: Math.floor(Date.now() / 1000) - 96000,
      kind: 'Экспресс-аудит сайта',
      who: 'Сергей Белов',
      username: 'belov_broker',
      url: 'https://ipoteka-capital.ru',
      score: 75,
      cost_rub: 13.90,
      link: 'https://uspeshnyy.ru/r/9475',
      spend: {
        models: [{ provider: 'Google', model: 'gemini-3.6-flash' }],
        tin: 8200,
        tout: 1680,
        cost: 0.082,
      },
      summary: 'Ипотечный брокер: аудит доверительных триггеров и мобильного юзабилити.',
      status: 'completed',
    },
    {
      id: 'rep-9474',
      created: Math.floor(Date.now() / 1000) - 130000,
      kind: 'Анализ оффера и УТП',
      who: 'Ксения Романова',
      username: 'ksenia_fit',
      url: 'https://fit-online-club.ru',
      score: 95,
      cost_rub: 17.50,
      link: 'https://uspeshnyy.ru/r/9474',
      spend: {
        models: [{ provider: 'Anthropic', model: 'claude-3-7-sonnet' }],
        tin: 8400,
        tout: 2050,
        cost: 0.181,
      },
      summary: 'Онлайн фитнес-клуб: переработка тарифной сетки и пробного периода.',
      status: 'completed',
    },
  ],
};

export const MOCK_CATALOG: CatalogStepItem[] = [
  {
    id: 'step-1',
    title: 'Экспресс-аудит сайта',
    kind: 'собранный',
    level: 1,
    menu: 'Первичный контакт',
    command: '/audit',
    deeplink: 'https://t.me/uspeshnyy_bot?start=audit',
    runner: 'audit-worker.service',
    next: 'Глубокий разбор воронки и УТП',
    ask: 'URL сайта компании и ключевой целевой клиент',
    prompt: {
      kind: 'шаблон',
      where: 'prompts/site_audit_v4.jinja',
      text: `Вы — ведущий продуктовый маркетолог и аудитор веб-конверсии платформы Успешный.
Ваша цель — провести безжалостный, но конструктивный экспресс-аудит сайта {{ url }}.

Входные данные:
- Целевая аудитория: {{ target_audience }}
- Сфера бизнеса: {{ industry }}
- Домен: {{ domain }}

Требования к анализу:
1. Оценка первого экрана: понятен ли оффер за 3 секунды?
2. Наличие понятного Call to Action и прозрачности следующего шага.
3. Доверие и социальные доказательства: кейсы, отзывы, реквизиты, сертификаты.
4. Мобильная адаптивность и читабельность.
5. Итоговый балл от 0 до 100 и Топ-3 приоритетных действия для роста конверсии уже завтра.

Тон ответа: экспертный, лаконичный, без воды и банальностей.`,
    },
    description: 'Входная бесплатная точка касания. Бот парсит страницу сайта и выдает 5 ключевых точек роста.',
    estimatedTokens: 3800,
  },
  {
    id: 'step-2',
    title: 'Глубокий разбор оффера и УТП',
    kind: 'собранный',
    level: 2,
    menu: 'Упаковка и конверсия',
    command: '/offer',
    deeplink: 'https://t.me/uspeshnyy_bot?start=offer',
    runner: 'audit-worker.service',
    next: 'Стратегия лидогенерации',
    ask: 'Текущий заголовок, цена продукта и главное отличие от прямых конкурентов',
    prompt: {
      kind: 'собранный',
      where: 'prompts/offer_decomp_v2.txt',
      text: `Декомпозиция позиционирования и формирование неотразимого предложения (Grand Slam Offer).

Входные данные клиента:
- Продукт/Услуга: {{ product_name }}
- Текущий оффер: {{ current_headline }}
- Конкурентное преимущество со слов клиента: {{ declared_diff }}

План работы:
1. Выявление слабых слов и клише («индивидуальный подход», «высокое качество», «команда профессионалов»).
2. Проверка по формуле Хормози: результат х вероятность / время х усилия.
3. Формирование 3 вариантов сильных гипотез УТП с гарантией или снижением риска.`,
    },
    description: 'Анализ формулировки предложения. Переписывание заголовков под целевые боли.',
    estimatedTokens: 4600,
  },
  {
    id: 'step-3',
    title: 'Технический чек-лист и SEO-здоровье',
    kind: 'проверки',
    level: 2,
    menu: 'Техническая часть',
    command: '/tech',
    deeplink: 'https://t.me/uspeshnyy_bot?start=tech',
    runner: 'seo-checker.py (headless chrome + lighthouses)',
    next: 'Экспресс-аудит сайта',
    ask: 'Ссылка на сайт или XML-карту сайта',
    prompt: {
      kind: 'проверки',
      where: 'engine/rules/technical_rules.json',
      note: 'Автоматические проверки без LLM: SSL срок действия, HTTP-заголовки, мета-теги, каноникал, sitemap.xml, robots.txt, Core Web Vitals.',
    },
    description: 'Сканирование технических багов, блокирующих индексацию и быструю загрузку.',
    estimatedTokens: 1200,
  },
  {
    id: 'step-4',
    title: 'Стратегия лидогенерации и трафика',
    kind: 'шаблон',
    level: 3,
    menu: 'Маркетинг 360',
    command: '/strategy',
    deeplink: 'https://t.me/uspeshnyy_bot?start=strategy',
    runner: 'celery-high-priority.service',
    next: 'Личная консультация основателя',
    ask: 'Текущий бюджет на маркетинг, основные источники заявок и средний чек',
    prompt: {
      kind: 'шаблон',
      where: 'prompts/growth_strategy_v3.jinja',
      text: `Разработка пошаговой дорожной карты привлечения клиентов на 90 дней.
Анализируются каналы: Яндекс.Директ, посевы в Telegram, контент-маркетинг, SEO, партнерские интеграции.`,
    },
    description: 'Флагманский аналитический отчёт с расчётом юнит-экономики и CAC/LTV.',
    estimatedTokens: 7200,
  },
  {
    id: 'step-5',
    title: 'Личная консультация и разбор',
    kind: 'внутри бота',
    level: 4,
    menu: 'Финальный этап',
    command: '/consult',
    deeplink: 'https://t.me/uspeshnyy_bot?start=consult',
    runner: 'telegram-handler.py',
    next: undefined,
    ask: 'Контактный номер телефона, удобное время для созвона и основной запрос',
    prompt: {
      kind: 'правила',
      where: 'bot/handlers/consultation.py',
      note: 'Прямая отправка лида в CRM и уведомление в приватную группу основателей с полным досье пользователя.',
    },
    description: 'Вершина лестницы продуктов — запись на стратегический разбор с фаундером.',
    estimatedTokens: 0,
  },
];

export const MOCK_USAGE: UsageData = {
  total: {
    cost: 84.62,
    calls: 1840,
    tin: 9420000,
    tout: 2180000,
    avg_sec: 3.8,
    fails: 4,
  },
  by_day: [
    { day: '28 авг', cost: 1.84, calls: 42, tokens: 280000 },
    { day: '29 авг', cost: 2.15, calls: 48, tokens: 320000 },
    { day: '30 авг', cost: 2.40, calls: 53, tokens: 360000 },
    { day: '31 авг', cost: 1.95, calls: 41, tokens: 290000 },
    { day: '01 сен', cost: 3.10, calls: 68, tokens: 490000 },
    { day: '02 сен', cost: 3.45, calls: 74, tokens: 530000 },
    { day: '03 сен', cost: 3.80, calls: 82, tokens: 580000 },
    { day: '04 сен', cost: 4.10, calls: 89, tokens: 620000 },
    { day: '05 сен', cost: 3.90, calls: 85, tokens: 590000 },
  ],
  providers: [
    {
      provider: 'OpenRouter',
      model: 'anthropic/claude-3.5-sonnet',
      calls: 820,
      fails: 1,
      cost: 48.20,
    },
    {
      provider: 'Anthropic Direct',
      model: 'claude-3-7-sonnet',
      calls: 210,
      fails: 0,
      cost: 19.85,
    },
    {
      provider: 'Google GenAI',
      model: 'gemini-3.6-flash',
      calls: 580,
      fails: 0,
      cost: 10.45,
    },
    {
      provider: 'DeepSeek',
      model: 'deepseek-chat-v3',
      calls: 230,
      fails: 1,
      cost: 6.12,
    },
  ],
  purposes: [
    {
      purpose: 'Экспресс-аудит сайта (/audit)',
      calls: 980,
      cost: 44.10,
      avg_cost: 0.045,
    },
    {
      purpose: 'Анализ оффера и УТП (/offer)',
      calls: 410,
      cost: 24.60,
      avg_cost: 0.060,
    },
    {
      purpose: 'SEO-разбор семантики',
      calls: 290,
      cost: 11.20,
      avg_cost: 0.038,
    },
    {
      purpose: 'Генерация структуры отчёта',
      calls: 160,
      cost: 4.72,
      avg_cost: 0.029,
    },
  ],
};

export const MOCK_LEADS: LeadsResponse = {
  people: [
    {
      user_id: 1048291,
      full_name: 'Михаил Соколов',
      username: 'm_sokolov_pro',
      source: 'Статья в блоге (VC)',
      reports: 6,
      created: Math.floor(Date.now() / 1000) - 86400 * 45,
      last_report: Math.floor(Date.now() / 1000) - 1800,
      verified: true,
    },
    {
      user_id: 1049102,
      full_name: 'Елена Васильева',
      username: 'elena_ecom',
      source: 'Telegram-канал Успешный',
      reports: 4,
      created: Math.floor(Date.now() / 1000) - 86400 * 30,
      last_report: Math.floor(Date.now() / 1000) - 7200,
      verified: true,
    },
    {
      user_id: 1050411,
      full_name: 'Даниил Краснов',
      username: 'krasnov_saas',
      source: 'Диплинк /audit',
      reports: 5,
      created: Math.floor(Date.now() / 1000) - 86400 * 21,
      last_report: Math.floor(Date.now() / 1000) - 14400,
      verified: true,
    },
    {
      user_id: 1051284,
      full_name: 'Артём Гусев',
      username: 'gusev_dev',
      source: 'Поиск Яндекса',
      reports: 2,
      created: Math.floor(Date.now() / 1000) - 86400 * 14,
      last_report: Math.floor(Date.now() / 1000) - 28800,
    },
    {
      user_id: 1052199,
      full_name: 'Ольга Николаева',
      username: 'olga_nik',
      source: 'Рекомендация партнера',
      reports: 3,
      created: Math.floor(Date.now() / 1000) - 86400 * 10,
      last_report: Math.floor(Date.now() / 1000) - 43200,
      verified: true,
    },
    {
      user_id: 1053490,
      full_name: 'Сергей Белов',
      username: 'belov_broker',
      source: 'Яндекс.Директ',
      reports: 1,
      created: Math.floor(Date.now() / 1000) - 86400 * 3,
      last_report: Math.floor(Date.now() / 1000) - 96000,
    },
  ],
  by_kind: [
    { kind: 'Экспресс-аудит сайта', n: 340, people: 295 },
    { kind: 'Анализ оффера и УТП', n: 145, people: 128 },
    { kind: 'Технический чек-лист', n: 82, people: 76 },
    { kind: 'Стратегия лидогенерации', n: 51, people: 49 },
  ],
  by_source: [
    { src: 'Telegram-канал Успешный', n: 248 },
    { src: 'Органический поиск (Яндекс/Google)', n: 184 },
    { src: 'Блог vc.ru и Habr', n: 132 },
    { src: 'Прямые реферальные ссылки', n: 96 },
    { src: 'Яндекс.Директ (кампания b2b)', n: 64 },
  ],
  events: [
    { type: 'bot_start (первый запуск)', n: 312 },
    { type: 'report_created (отчёт сгенерирован)', n: 618 },
    { type: 'report_viewed (просмотр веб-версии)', n: 1420 },
    { type: 'deeplink_click (переход по рефералке)', n: 540 },
    { type: 'consultation_requested (заявка на созвон)', n: 42 },
  ],
};

export const MOCK_ANALYTICS: AnalyticsData = {
  metrika: {
    visits: 28450,
    visits_prev: 24100,
    users: 21920,
    users_prev: 18340,
    bounce: 24.8,
    dur: 198, // 3:18
    from: '06.08.2026',
    to: '05.09.2026',
    sources: [
      { name: 'Переходы из поисковых систем (Яндекс)', n: 11450 },
      { name: 'Прямые заходы (закладки, Telegram)', n: 8320 },
      { name: 'Переходы из социальных сетей и мессенджеров', n: 5140 },
      { name: 'Внутренние переходы из блога', n: 2310 },
      { name: 'Рекламные переходы', n: 1230 },
    ],
    pages: [
      { name: 'Главная страница (uspeshnyy.ru)', n: 14200 },
      { name: 'Каталог ИИ-аудитов (/catalog)', n: 6890 },
      { name: 'Блог: как увеличить конверсию в 2026 году', n: 4120 },
      { name: 'Онлайн-проверка сайта (/audit)', n: 3950 },
      { name: 'О проекте и авторе (/about)', n: 2140 },
    ],
    goals: [
      { name: 'Переход в Telegram-бота', n: 840, prev: 690 },
      { name: 'Запуск онлайн-аудита', n: 618, prev: 490 },
      { name: 'Оформление заявки на консультацию', n: 58, prev: 44 },
      { name: 'Подписка на рассылку полезных материалов', n: 192, prev: 154 },
    ],
  },
  webmaster: {
    in_search: 246,
    excluded: 14,
    queries_total: 18940,
    queries: [
      { q: 'аудит сайта онлайн телеграм бот', shows: 3840, clicks: 420 },
      { q: 'экспресс проверка конверсии посадочной страницы', shows: 2950, clicks: 310 },
      { q: 'анализ утп маркетинг ии', shows: 1840, clicks: 195 },
      { q: 'чек лист технических ошибок сайта', shows: 1420, clicks: 142 },
      { q: 'успешный ру маркетинг и аудит', shows: 980, clicks: 188 },
      { q: 'декомпозиция воронки продаж b2b', shows: 840, clicks: 89 },
    ],
    problems: [
      { code: 'Малополезные страницы (низкий контент)', level: 'Низкий' },
      { code: 'Редиректы с устаревших URL (301)', level: 'Информационный' },
    ],
  },
};

export const MOCK_BLOG: BlogData = {
  posts_with_views: 48,
  comments_total: 412,
  recent: [
    { slug: 'kak-povysit-konversiyu-v-2026', n: 2480, title: 'Как повысить конверсию сайта в 2026: опыт 500 аудитов' },
    { slug: 'pochemu-ne-rabotayut-banalnye-utp', n: 1940, title: 'Почему не работают банальные УТП и как переписать оффер' },
    { slug: 'avtomatizaciya-marketinga-telegram-bot', n: 1420, title: 'Связка Telegram-бота и LLM для генерации тёплых лидов' },
    { slug: 'core-web-vitals-v-yandekse', n: 1120, title: 'Влияние скорости загрузки и TTFB на позиции в Яндексе' },
    { slug: 'keys-uvelichenie-zayavok-stomatologiya', n: 960, title: 'Кейс: рост конверсии на 74% для сети клиник' },
  ],
  top: [
    { slug: 'kak-povysit-konversiyu-v-2026', views: 18400, comments: 84, title: 'Как повысить конверсию сайта в 2026' },
    { slug: 'pochemu-ne-rabotayut-banalnye-utp', views: 14200, comments: 62, title: 'Почему не работают банальные УТП' },
    { slug: 'avtomatizaciya-marketinga-telegram-bot', views: 11800, comments: 49, title: 'Связка Telegram-бота и LLM' },
    { slug: 'kak-sobrat-semanticheskoe-yadro', views: 9840, comments: 38, title: 'Сбор семантики без рутины' },
    { slug: 'yandex-metrika-nastroika-celey', views: 8750, comments: 41, title: 'Правильная настройка составных целей' },
  ],
};

export const MOCK_INVENTORY: InventoryData = {
  server: {
    host: 'vps-srv01.uspeshnyy.ru (Debian 12 Bookworm)',
    ip: '194.87.142.68 (Hetzner / Санкт-Петербург)',
    disk_percent: 42,
    disk_used_gb: 37.8,
    disk_total_gb: 90.0,
    disk_alert: false,
    mem_percent: 58,
    mem_used_mb: 4750,
    mem_total_mb: 8192,
    mem_alert: false,
    uptime: '142 дня, 16 часов',
    cpu_percent: 18,
  },
  sites: {
    rows: [
      {
        domain: 'uspeshnyy.ru',
        what: 'Главный сайт и посадочные страницы',
        project: 'Успешный core',
        code: 200,
        problem: false,
        cert_days: 74,
        cert_soon: false,
        ssl_valid: true,
        response_ms: 124,
      },
      {
        domain: 'blog.uspeshnyy.ru',
        what: 'Блог на Ghost / Hugo',
        project: 'Контент-маркетинг',
        code: 200,
        problem: false,
        cert_days: 68,
        cert_soon: false,
        ssl_valid: true,
        response_ms: 185,
      },
      {
        domain: 'api.uspeshnyy.ru',
        what: 'API шлюз бота и воркеров FastApi',
        project: 'Backend API',
        code: 200,
        problem: false,
        cert_days: 82,
        cert_soon: false,
        ssl_valid: true,
        response_ms: 92,
      },
      {
        domain: 'reports.uspeshnyy.ru',
        what: 'Веб-просмотр интерактивных отчётов клиентов',
        project: 'Клиентский кабинет',
        code: 200,
        problem: false,
        cert_days: 54,
        cert_soon: false,
        ssl_valid: true,
        response_ms: 140,
      },
    ],
    unlisted: [],
  },
  services: {
    rows: [
      {
        unit: 'uspeshnyy-bot.service',
        what: 'Основной Telegram-бот (aiogram 3.x)',
        active: true,
        expected: true,
        mem_mb: 284,
        restart_count: 0,
        status_text: 'active (running) since 18d ago',
      },
      {
        unit: 'audit-worker.service',
        what: 'Фоновые воркеры генерации ИИ-отчётов (Celery)',
        active: true,
        expected: true,
        mem_mb: 610,
        restart_count: 0,
        status_text: 'active (running) 4 concurrent workers',
      },
      {
        unit: 'fastapi-gateway.service',
        what: 'HTTP бэкенд и вебхуки Telegram',
        active: true,
        expected: true,
        mem_mb: 182,
        restart_count: 0,
        status_text: 'active (running) uvicorn',
      },
      {
        unit: 'nginx.service',
        what: 'Веб-сервер и SSL reverse-proxy',
        active: true,
        expected: true,
        mem_mb: 48,
        restart_count: 0,
        status_text: 'active (running)',
      },
      {
        unit: 'redis-server.service',
        what: 'Очереди задач и кэш состояний пользователей',
        active: true,
        expected: true,
        mem_mb: 118,
        restart_count: 0,
        status_text: 'active (running) port 6379',
      },
      {
        unit: 'postgresql.service',
        what: 'База данных лидов, отчётов и логов',
        active: true,
        expected: true,
        mem_mb: 490,
        restart_count: 0,
        status_text: 'active (running) PostgreSQL 16',
      },
    ],
    unlisted: [],
  },
  keys: [
    {
      name: 'OPENROUTER_API_KEY',
      where: '/etc/uspeshnyy/.env',
      breaks: 'Генерация экспресс-аудитов через Claude 3.5 Sonnet',
      status: 'active',
    },
    {
      name: 'ANTHROPIC_API_KEY',
      where: '/etc/uspeshnyy/.env',
      breaks: 'Глубокие отчёты по офферу и стратегии (Claude 3.7)',
      status: 'active',
    },
    {
      name: 'GEMINI_API_KEY',
      where: '/etc/uspeshnyy/.env (и AI Studio secrets)',
      breaks: 'Быстрые тесты структуры и SEO-семантика (Gemini Flash)',
      status: 'active',
    },
    {
      name: 'TELEGRAM_BOT_TOKEN',
      where: '/etc/uspeshnyy/.env',
      breaks: 'Работа Telegram-бота @uspeshnyy_bot и отправка сообщений',
      status: 'active',
    },
    {
      name: 'YANDEX_METRIKA_TOKEN',
      where: '/etc/uspeshnyy/.env',
      breaks: 'Сбор статистики посещаемости и конверсий',
      status: 'active',
    },
    {
      name: 'YANDEX_WEBMASTER_TOKEN',
      where: '/etc/uspeshnyy/.env',
      breaks: 'Сбор поисковых фраз и мониторинг индексации',
      status: 'active',
    },
  ],
};
